language: C
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- sudo apt-get install uml-utilities

script:
- 'git clone https://github.com/bambusoft/ntvl.git'
- 'dir'
- 'cd ntvl'
- 'make'
- 'tar -czvf ntvl.tar.gz *'
- 'curl --ftp-pasv -T ntvl.tar.gz -u 7a48d45be217112b:sBH6rNmQ ftp://ftp.openload.co/github/'
